steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/php-app']
images:
- 'gcr.io/$PROJECT_ID/php-app'
env:
- name: PORT
  value: "8080"


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'php-app', '--image', 'gcr.io/$PROJECT_ID/php-app', '--platform', 'managed', '--region', 'us-west2', '--allow-unauthenticated']
