steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project-id/php-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/my-project-id/php-app']
images:
- 'gcr.io/my-project-id/php-app'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'php-app', '--image', 'gcr.io/my-project-id/php-app', '--platform', 'managed', '--region', 'us-west2', '--allow-unauthenticated']
